export const ENGINE_ERROR_CODES = Object.freeze({
  UNSUPPORTED_SCHEMA_VERSION: "ENGINE_UNSUPPORTED_SCHEMA_VERSION",
  INVALID_IDENTITY: "ENGINE_INVALID_IDENTITY",
  INVALID_ITEM_LEVEL: "ENGINE_INVALID_ITEM_LEVEL",
  INVALID_RARITY: "ENGINE_INVALID_RARITY",
  INVALID_REVISION: "ENGINE_INVALID_REVISION",
  INVALID_MODIFIER_LIST: "ENGINE_INVALID_MODIFIER_LIST",
  DUPLICATE_MODIFIER_INSTANCE: "ENGINE_DUPLICATE_MODIFIER_INSTANCE",
  INVALID_MODIFIER: "ENGINE_INVALID_MODIFIER",
  INVALID_HISTORY: "ENGINE_INVALID_HISTORY",
  INVALID_STATE: "ENGINE_INVALID_STATE",
  UNKNOWN_ENGINE_FIELD: "ENGINE_UNKNOWN_FIELD"
});

export const ENGINE_RULE_ERROR_CODES = Object.freeze({
  UNKNOWN_ITEM_CLASS: "ENGINE_UNKNOWN_ITEM_CLASS",
  UNKNOWN_BASE_TYPE: "ENGINE_UNKNOWN_BASE_TYPE",
  BASE_CLASS_MISMATCH: "ENGINE_BASE_CLASS_MISMATCH",
  UNKNOWN_MODIFIER: "ENGINE_UNKNOWN_MODIFIER",
  UNKNOWN_MODIFIER_DOMAIN: "ENGINE_UNKNOWN_MODIFIER_DOMAIN",
  UNKNOWN_GENERATION_TYPE: "ENGINE_UNKNOWN_GENERATION_TYPE",
  MODIFIER_ITEM_LEVEL_NOT_MET: "ENGINE_MODIFIER_ITEM_LEVEL_NOT_MET",
  INVALID_WEIGHT_STRUCTURE: "ENGINE_INVALID_WEIGHT_STRUCTURE",
  INVALID_CATALOG_DATA: "ENGINE_INVALID_CATALOG_DATA",
  DISPLAY_TIER_CONTEXT_REQUIRED: "ENGINE_DISPLAY_TIER_CONTEXT_REQUIRED",
  RULE_DATA_NOT_AVAILABLE: "ENGINE_RULE_DATA_NOT_AVAILABLE"
});

export const ENGINE_ELIGIBILITY_CODES = Object.freeze({
  CONTEXT_INVALID: "ENGINE_ELIGIBILITY_CONTEXT_INVALID",
  ITEM_CLASS_MISMATCH: "ENGINE_ELIGIBILITY_ITEM_CLASS_MISMATCH",
  ITEM_CLASS_UNRESOLVED: "ENGINE_ELIGIBILITY_ITEM_CLASS_UNRESOLVED",
  BASE_TYPE_MISMATCH: "ENGINE_ELIGIBILITY_BASE_TYPE_MISMATCH",
  ITEM_LEVEL_NOT_MET: "ENGINE_ELIGIBILITY_ITEM_LEVEL_NOT_MET",
  ITEM_LEVEL_UNRESOLVED: "ENGINE_ELIGIBILITY_ITEM_LEVEL_UNRESOLVED",
  GENERATION_TYPE_EXCLUDED: "ENGINE_ELIGIBILITY_GENERATION_TYPE_EXCLUDED",
  GENERATION_TYPE_UNRESOLVED: "ENGINE_ELIGIBILITY_GENERATION_TYPE_UNRESOLVED",
  SPECIAL_SOURCE_EXCLUDED: "ENGINE_ELIGIBILITY_SPECIAL_SOURCE_EXCLUDED",
  DOMAIN_UNRESOLVED: "ENGINE_ELIGIBILITY_DOMAIN_UNRESOLVED",
  DOMAIN_NOT_REQUIRED: "ENGINE_ELIGIBILITY_DOMAIN_NOT_REQUIRED",
  TAG_MISMATCH: "ENGINE_ELIGIBILITY_TAG_MISMATCH",
  TAG_DATA_MISSING: "ENGINE_ELIGIBILITY_TAG_DATA_MISSING",
  ZERO_WEIGHT: "ENGINE_ELIGIBILITY_ZERO_WEIGHT",
  WEIGHT_MISSING: "ENGINE_ELIGIBILITY_WEIGHT_MISSING",
  DUPLICATE_MODIFIER: "ENGINE_ELIGIBILITY_DUPLICATE_MODIFIER",
  MOD_GROUP_CONFLICT: "ENGINE_ELIGIBILITY_MOD_GROUP_CONFLICT",
  MOD_GROUP_UNRESOLVED: "ENGINE_ELIGIBILITY_MOD_GROUP_UNRESOLVED",
  PREFIX_CAPACITY_REACHED: "ENGINE_ELIGIBILITY_PREFIX_CAPACITY_REACHED",
  SUFFIX_CAPACITY_REACHED: "ENGINE_ELIGIBILITY_SUFFIX_CAPACITY_REACHED",
  CAPACITY_UNRESOLVED: "ENGINE_ELIGIBILITY_CAPACITY_UNRESOLVED",
  CATALOG_INVALID: "ENGINE_ELIGIBILITY_CATALOG_INVALID"
});

export const ENGINE_ACTION_CODES = Object.freeze({
  UNKNOWN: "ENGINE_ACTION_UNKNOWN",
  CONTEXT_INVALID: "ENGINE_ACTION_CONTEXT_INVALID",
  ITEM_RARITY_ALLOWED: "ENGINE_ACTION_ITEM_RARITY_ALLOWED",
  ITEM_RARITY_NOT_ALLOWED: "ENGINE_ACTION_ITEM_RARITY_NOT_ALLOWED",
  RARITY_TRANSITION_AVAILABLE: "ENGINE_ACTION_RARITY_TRANSITION_AVAILABLE",
  RARITY_UNRESOLVED: "ENGINE_ACTION_RARITY_UNRESOLVED",
  ELIGIBILITY_AVAILABLE: "ENGINE_ACTION_ELIGIBILITY_AVAILABLE",
  NO_ELIGIBLE_MODIFIER: "ENGINE_ACTION_NO_ELIGIBLE_MODIFIER",
  ELIGIBILITY_UNRESOLVED: "ENGINE_ACTION_ELIGIBILITY_UNRESOLVED",
  SELECTION_REQUIRED: "ENGINE_ACTION_SELECTION_REQUIRED",
  SELECTION_COUNT_UNRESOLVED: "ENGINE_ACTION_SELECTION_COUNT_UNRESOLVED",
  RANDOM_REMOVAL_REQUIRED: "ENGINE_ACTION_RANDOM_REMOVAL_REQUIRED",
  REMOVAL_RULE_UNRESOLVED: "ENGINE_ACTION_REMOVAL_RULE_UNRESOLVED",
  MUTATION_DEFERRED: "ENGINE_ACTION_MUTATION_DEFERRED",
  UNSUPPORTED_MECHANIC: "ENGINE_ACTION_UNSUPPORTED_MECHANIC",
  CATALOG_INVALID: "ENGINE_ACTION_CATALOG_INVALID"
});

export class EngineValidationError extends Error {
  constructor(code, message, path = "", details = {}) {
    super(message);
    this.name = "EngineValidationError";
    this.code = code;
    this.path = path;
    this.details = details;
  }

  toJSON() {
    return { code: this.code, message: this.message, path: this.path, details: this.details };
  }
}

export function engineError(code, message, path, details) {
  return new EngineValidationError(code, message, path, details);
}
