export const ENGINE_ERROR_CODES = Object.freeze({
  UNSUPPORTED_SCHEMA_VERSION: "ENGINE_UNSUPPORTED_SCHEMA_VERSION",
  INVALID_IDENTITY: "ENGINE_INVALID_IDENTITY",
  INVALID_ITEM_LEVEL: "ENGINE_INVALID_ITEM_LEVEL",
  INVALID_RARITY: "ENGINE_INVALID_RARITY",
  INVALID_REVISION: "ENGINE_INVALID_REVISION",
  INVALID_MODIFIER_LIST: "ENGINE_INVALID_MODIFIER_LIST",
  DUPLICATE_MODIFIER_INSTANCE: "ENGINE_DUPLICATE_MODIFIER_INSTANCE",
  INVALID_MODIFIER: "ENGINE_INVALID_MODIFIER",
  INVALID_HISTORY: "ENGINE_INVALID_HISTORY",
  INVALID_STATE: "ENGINE_INVALID_STATE",
  UNKNOWN_ENGINE_FIELD: "ENGINE_UNKNOWN_FIELD"
});

export const ENGINE_RULE_ERROR_CODES = Object.freeze({
  UNKNOWN_ITEM_CLASS: "ENGINE_UNKNOWN_ITEM_CLASS",
  UNKNOWN_BASE_TYPE: "ENGINE_UNKNOWN_BASE_TYPE",
  BASE_CLASS_MISMATCH: "ENGINE_BASE_CLASS_MISMATCH",
  UNKNOWN_MODIFIER: "ENGINE_UNKNOWN_MODIFIER",
  UNKNOWN_MODIFIER_DOMAIN: "ENGINE_UNKNOWN_MODIFIER_DOMAIN",
  UNKNOWN_GENERATION_TYPE: "ENGINE_UNKNOWN_GENERATION_TYPE",
  MODIFIER_ITEM_LEVEL_NOT_MET: "ENGINE_MODIFIER_ITEM_LEVEL_NOT_MET",
  INVALID_WEIGHT_STRUCTURE: "ENGINE_INVALID_WEIGHT_STRUCTURE",
  INVALID_CATALOG_DATA: "ENGINE_INVALID_CATALOG_DATA",
  DISPLAY_TIER_CONTEXT_REQUIRED: "ENGINE_DISPLAY_TIER_CONTEXT_REQUIRED",
  RULE_DATA_NOT_AVAILABLE: "ENGINE_RULE_DATA_NOT_AVAILABLE"
});

export class EngineValidationError extends Error {
  constructor(code, message, path = "", details = {}) {
    super(message);
    this.name = "EngineValidationError";
    this.code = code;
    this.path = path;
    this.details = details;
  }

  toJSON() {
    return { code: this.code, message: this.message, path: this.path, details: this.details };
  }
}

export function engineError(code, message, path, details) {
  return new EngineValidationError(code, message, path, details);
}
